### ISSUE TITLE
[Feature]: Worker

### ISSUE THREAD

**Issue by Mikkek** [kevinvinther/pomodoro#4]
### Issues

- [X] I have checked [existing issues](https://github.com/kevinvinther/pomodoro/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Short Feature Description

A simple worker that slowly increases the score value

### (Optional) Long Feature Description

The worker is an independent functionality that manipulates the score value, independently of the default +1 score for each second (see https://github.com/kevinvinther/pomodoro/issues/5).

### Goals

* [ ] Increase the score slowly, e.g. +5/sec
* [ ] Activate the worker
* [ ] Deactivate the worker

**Comment by kevinvinther** [comment]
https://github.com/kevinvinther/pomodoro/commit/ea9d0b4bf7568abe329efd943adf91aa084ef739
